# Generated by Django 4.0.2 on 2022-02-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryBanIp',
        ),
    ]
