# Generated by Django 4.0.2 on 2022-02-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
